/**
 * Resolves a news category to its placeholder banner.
 *
 * The banner is inverted against the page — dark art on a light page and the
 * reverse — so the band reads as artwork rather than as a washed-out extension
 * of the card. That inversion CANNOT live inside the SVG: an <img> can only see
 * `prefers-color-scheme`, and this site pins `defaultTheme="dark"` in
 * app/layout.tsx regardless of the OS, so the two disagree for anyone whose OS
 * is light. Verified by dumping the DOM with the OS forced each way — the html
 * element carried `class="... dark"` both times.
 *
 * So the caller passes the resolved theme and gets the right file. Art is
 * generated by `pnpm brand:banners`.
 */

const SLUGS: Record<string, string> = {
  Updates: 'updates',
  Security: 'security',
  Ecosystem: 'ecosystem',
  Community: 'community',
  Development: 'development',
}

export function categoryBannerSrc(category: string, resolvedTheme: string | undefined): string {
  // resolvedTheme is undefined until mount. Falling back to 'dark' matches the
  // configured defaultTheme, so the pre-hydration guess is right for almost
  // every visit and there is no flash.
  const page = resolvedTheme === 'light' ? 'light' : 'dark'
  const slug = SLUGS[category] ?? 'updates'
  return `/news/images/placeholder-${slug}-on-${page}.svg`
}
