import type { Metadata } from "next";
import Script from "next/script";
import { Inter, JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Navigation from "./components/Navigation";
import { Providers } from "./providers";
import { OrganizationJsonLd, WebsiteJsonLd, CryptocurrencyJsonLd } from "./components/JsonLd";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://ethereumclassic.com"),
  title: "Ethereum Classic — Immutable Infrastructure for Global Finance",
  description:
    "The only mature Proof-of-Work blockchain with native smart contracts. Permissionless, censorship-resistant, and secured by dedicated mining infrastructure operating continuously since 2015.",
  keywords: [
    "Ethereum Classic",
    "ETC",
    "cryptocurrency",
    "blockchain",
    "proof of work",
    "smart contracts",
    "mining",
    "DeFi",
    "dApps",
    "ETCHash",
    "Olympia",
    "ECIP-1111",
    "ECIP-1112",
    "ECIP-1121",
    "ECIP-1122",
    "Fusaka",
    "Glamsterdam",
    "EVM upgrade",
    "EVM compatibility",
    "Dencun",
    "Pectra",
    "Solidity compatibility",
    "EIP-3198",
    "CLARITY Act",
    "GENIUS Act",
    "MiCA",
    "FSA Green List",
    "digital commodity",
    "decentralized asset",
    "regulated stablecoin",
    "Japan crypto-asset",
  ],
  authors: [{ name: "Ethereum Classic" }],
  creator: "Ethereum Classic",
  openGraph: {
    title: "Ethereum Classic — Immutable Infrastructure for Global Finance",
    description: "The only mature Proof-of-Work blockchain with native smart contracts. Permissionless, censorship-resistant, and secured by dedicated mining infrastructure operating continuously since 2015.",
    // Relative for the same reason as the canonical above: routes that inherit
    // this block instead of declaring their own would otherwise all advertise
    // the homepage URL on their share cards.
    url: "./",
    siteName: "Ethereum Classic",
    locale: "en_US",
    type: "website",
    images: [{ url: "/og.png", width: 1200, height: 630, alt: "Ethereum Classic — Proof-of-Work Smart Contracts", type: "image/png" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Ethereum Classic — Immutable Infrastructure for Global Finance",
    description: "The only mature Proof-of-Work blockchain with native smart contracts. Permissionless, censorship-resistant, secured by dedicated mining infrastructure operating continuously since 2015.",
    images: [{ url: "/og.png", alt: "Ethereum Classic — the only mature Proof-of-Work blockchain with native smart contracts" }],
  },
  // Generated by `pnpm brand:icons` from brand/logo/etc-mark.svg. favicon.ico
  // stays at the root because browsers and crawlers request that exact path
  // without reading any <link>; everything else lives under /icons.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
      { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    // 180x180 is Apple's size. The file this replaced was 192x192, which is
    // Android's — iOS rescaled it silently rather than failing.
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  alternates: {
    // Relative, NOT the absolute site URL. In the App Router `alternates` is
    // inherited by every child route, so a literal URL here stamps the homepage
    // as the canonical of all 300+ pages and asks Google to drop them. "./"
    // resolves against metadataBase AND the current route.
    canonical: "./",
    types: {
      'application/rss+xml': '/news/feed.xml',
      'application/atom+xml': '/news/atom.xml',
      'application/feed+json': '/news/feed.json',
    },
  },
  other: { "color-scheme": "light dark" },
  formatDetection: { telephone: false, email: false },
  appleWebApp: {
    capable: true,
    title: "Ethereum Classic",
    statusBarStyle: "black-translucent",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${jetbrainsMono.variable}`}
    >
      <head>
        <OrganizationJsonLd />
        <WebsiteJsonLd />
        <CryptocurrencyJsonLd />
      </head>
      <body className="relative isolate min-h-dvh antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <a
              href="#main-content"
              className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-[var(--brand-green)] focus:px-4 focus:py-2 focus:text-[var(--background)] focus:outline-none"
            >
              Skip to main content
            </a>
            <Navigation />
            <main id="main-content" className="relative z-10 pt-16">
              {children}
            </main>
          </Providers>
        </ThemeProvider>
        <Script
          src="https://static.cloudflareinsights.com/beacon.min.js"
          data-cf-beacon='{"token": "977635a2225b49e9929b117b3be16267"}'
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
