import type { MetadataRoute } from 'next';

/**
 * Icons are generated by `pnpm brand:icons`. Before this was corrected, all three
 * entries here pointed at files that did not exist (`/icon.svg`,
 * `/android-chrome-192x192.png`, `/android-chrome-512x512.png`) — a manifest
 * referencing a missing icon fails silently, so the PWA install prompt simply
 * never offered an icon and nothing surfaced an error.
 *
 * The colors are read from app/styles/tokens.css rather than restated from
 * memory; the previous `#3AB83A` matched no token in this repo.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Ethereum Classic — Proof-of-Work Smart Contracts',
    short_name: 'ETC',
    description:
      'The only mature Proof-of-Work blockchain with smart contracts. Get wallets, buy ETC, and discover apps.',
    start_url: '/',
    display: 'standalone',
    background_color: '#0a0f10', // --background, dark theme (the site's default)
    theme_color: '#007a53', // --brand-green
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      // Android crops an adaptive icon to an arbitrary shape and only guarantees
      // the center 80% circle, so this variant carries a much larger inset.
      { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
